apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        rm -rf __pycache__ .pytest_cache dist *.pyc
