apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-unittests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Installing test dependencies..."
        if [ -f requirements.txt ]; then
          pip install --no-cache-dir -r requirements.txt
        else
          echo "⚠️ File requirements.txt non trovato. Nessuna dipendenza installata."
        fi

        echo "Eseguo i test..."
        i
