apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-unittests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        pip install -r requirements.txt
        python -m unittest discover
