apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/AlfaScorpii96bis/ci-cd-final-project
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"

    - name: lint
      runAfter: [fetch-source]
      taskRef:
        name: lint-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: test
      runAfter: [lint]
      taskRef:
        name: test-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      runAfter: [test]
      ta
